apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: modiapersonoversikt-api
  namespace: personoversikt
  labels:
    team: personoversikt
spec:
  image: "{{image}}"
  port: 8080
  team: personoversikt
  liveness:
    path: /modiapersonoversikt-api/internal/isAlive
    initialDelay: 50
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /modiapersonoversikt-api/internal/isReady
    initialDelay: 50
    timeout: 1
  prometheus:
    enabled: true
    path: /modiapersonoversikt-api/internal/prometheus
  secureLogs:
    enabled: true
  resources:
    requests:
      cpu: 1000m
      memory: 4096Mi
    limits:
      cpu: 2000m
      memory: 8192Mi
  ingresses:
    - https://modiapersonoversikt-api.nais.adeo.no
    - https://app.adeo.no/modiapersonoversikt-api
    - https://modapp.adeo.no/modiapersonoversikt-api
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 60
  vault:
    enabled: true
    paths:
      - kvPath: /serviceuser/data/prod/srvmodiabrukerdialog
        mountPath: /var/run/secrets/nais.io/service_user
      - kvPath: /serviceuser/data/prod/srvssolinux
        mountPath: /var/run/secrets/nais.io/srvssolinux
      - kvPath: /apikey/appdynamics/prod
        mountPath: /var/run/secrets/nais.io/vault
  leaderElection: true
  webproxy: true
  azure:
    application:
      enabled: true
      tenant: nav.no
      claims:
        extra:
          - "NAVident"
  accessPolicy:
    inbound:
      rules:
        - application: modiapersonoversikt
          namespace: personoversikt
          cluster: prod-fss
  env:
    - name: APP_ENVIRONMENT_NAME
      value: "p"
    - name: APP_VERSION
      value: "{{ version }}"
    - name: MODIA_CLIENT_ID
      value: "modialogin-p"
    - name: MODIA_REFRESH_URL
      value: "https://app.adeo.no/modialogin/api/refresh"
    - name: ISSO_DISCOVERY_URL
      value: "https://isso.adeo.no/isso/oauth2/.well-known/openid-configuration"
    - name: SECURITY_TOKEN_SERVICE_DISCOVERY_URL
      value: "https://security-token-service.nais.adeo.no/rest/v1/sts/.well-known/openid-configuration"
    - name: SECURITYTOKENSERVICE_URL
      value: "https://sts.adeo.no/SecurityTokenServiceProvider/"
    - name: BRUKERVARSELV1_ENDPOINTURL
      value: "https://app.adeo.no/varsel/ws/Brukervarsel/v1"
    - name: FELLES_KODEVERK_URL
      value: "https://kodeverk.nais.adeo.no"
    - name: LDAP_BASEDN
      value: "dc=adeo,dc=no"
    - name: LDAP_DOMAIN
      value: "ADEO.NO"
    - name: LDAP_SERVICEUSER_BASEDN
      value: "ou=ServiceAccounts,dc=adeo,dc=no"
    - name: LDAP_URL
      value: "ldaps://ldapgw.adeo.no"
    - name: LDAP_USER_BASEDN
      value: "ou=NAV,ou=BusinessUnits,dc=adeo,dc=no"
    - name: SAF_GRAPHQL_URL
      value: "https://saf.nais.adeo.no/graphql"
    - name: SAF_HENTDOKUMENT_URL
      value: "https://saf.nais.adeo.no/rest/hentdokument"
    - name: SAKOGBEHANDLING_ENDPOINTURL
      value: "https://modapp.adeo.no/sakogbehandling/ws/SakOgBehandling_v1"
    - name: SERVER_AKTIVITETSPLAN_URL
      value: "https://app.adeo.no"
    - name: SERVER_ARENA_URL
      value: "http://arena.adeo.no/forms/arenaMod.html"
    - name: SERVER_DREK_URL
      value: "https://drek.nais.adeo.no/"
    - name: SERVER_GOSYS_URL
      value: "https://wasapp.adeo.no"
    - name: SERVER_NORG2_FRONTEND_URL
      value: "https://norg2-frontend.nais.adeo.no"
    - name: SERVER_PESYS_URL
      value: "https://wasapp.adeo.no"
    - name: SERVER_VEILARBPORTEFOLJEFLATEFS_URL
      value: "https://app.adeo.no/veilarbportefoljeflatefs"
    - name: SERVER_AAREG_URL
      value: "https://modapp.adeo.no/aareg-web"
    - name: TJENESTER_URL
      value: "https://tjenester.nav.no"
    - name: UNLEASH_API_URL
      value: "https://unleash.nais.io/api/"
    - name: UTBETALING_V1_ENDPOINTURL
      value: "https://wasapp.adeo.no/nav-utbetaldata-ws/virksomhet/Utbetaling_v1"
    - name: VEILARBOPPFOLGINGAPI_URL
      value: "https://veilarboppfolging.nais.adeo.no/veilarboppfolging/api"
    - name: VIRKSOMHET_DIGITALKONTAKINFORMASJON_V1_ENDPOINTURL
      value: "https://dkif.nais.adeo.no/ws/DigitalKontaktinformasjon/v1"
    - name: DKIF_REST_URL
      value: "https://dkif.nais.adeo.no/"
    - name: VIRKSOMHET_FORELDREPENGER_V2_ENDPOINTURL
      value: "https://modapp.adeo.no/infotrygd-ws/ForeldrepengerService/v2"
    - name: VIRKSOMHET_OPPFOLGING_V1_ENDPOINTURL
      value: "https://arena.adeo.no/ail_ws/Oppfoelging_v1"
    - name: EREG_ENDPOINTURL
      value: "https://modapp.adeo.no/ereg/"
    - name: KONTOREGISTER_REST_URL
      value: "https://sokos-kontoregister-person.intern.nav.no/kontoregister/api/kontoregister"
    - name: VIRKSOMHET_PERSON_V3_ENDPOINTURL
      value: "https://app.adeo.no/tpsws-aura/ws/Person/v3"
    - name: VIRKSOMHET_PERSONSOK_V1_ENDPOINTURL
      value: "https://app.adeo.no/tpsws-aura/ws/Personsok/v1"
    - name: VIRKSOMHET_PLEIEPENGER_V1_ENDPOINTURL
      value: "https://modapp.adeo.no/infotrygd-ws/Pleiepenger/v1"
    - name: VIRKSOMHET_SYKEPENGER_V2_ENDPOINTURL
      value: "https://modapp.adeo.no/infotrygd-ws/SykepengerService/v2"
    - name: VIRKSOMHET_YTELSESKONTRAKT_V3_ENDPOINTURL
      value: "https://arena.adeo.no/ail_ws/Ytelseskontrakt_v3"
    - name: SF_HENVENDELSE_URL
      value: "https://sf-henvendelse.intern.nav.no/api"
    - name: PDL_API_URL
      value: "https://pdl-api.nais.adeo.no/graphql"
    - name: PERSONFORVALTER_URL
      value: "https://pdl-web.intern.nav.no/endreperson"
    - name: OPPGAVE_BASEURL
      value: "https://oppgave.nais.adeo.no/"
    - name: NORG2_BASEURL
      value: "https://app.adeo.no/norg2"
    - name: PREFETCH_NORG_ANSATTLISTE_SCHEDULE
      value: "0 0 7,19 * * *"
    - name: SAKSOVERSIKT_PRODSETTNINGSDATO
      value: "2016-06-04"
    - name: FJERN_SOKNADER_FOR_DATO
      value: "2014-12-09"
    - name: HASTEKASSERING_TILGANG
      value: "G110867,S111498,W152868,N127626,B152650,B152650,B114736,H110866,J121487,O122413,T110884,V114843,E110861,U136854"
    - name: INTERNAL_TILGANG
      value: "U143410"
    - name: CXF_SECURE_LOG
      value: "enabled"
    - name: AXSYS_URL
      value: "https://axsys.nais.adeo.no"
    - name: AXSYS_CLUSTER
      value: "prod-fss"
    - name: NOM_URL
      value: "https://nom-api.intern.nav.no"
    - name: SKJERMEDE_PERSONER_PIP_CLUSTER
      value: "prod-gcp"
    - name: SKJERMEDE_PERSONER_PIP_URL
      value: "https://skjermede-personer-pip.intern.nav.no"
    - name: ARENA_SAK_VEDTAK_URL
      value: "https://arena.adeo.no/arena_ws/services/ArenaSakVedtakService"
    - name: DITTNAV_EVENTER_MODIA_URL
      value: "https://app.adeo.no/dittnav-eventer-modia"