apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: modiapersonoversikt-api-q0
  namespace: personoversikt
  labels:
    team: personoversikt
spec:
  image: "{{image}}"
  port: 8080
  team: personoversikt
  liveness:
    path: /modiapersonoversikt-api/internal/isAlive
    initialDelay: 50
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /modiapersonoversikt-api/internal/isReady
    initialDelay: 50
    timeout: 1
  prometheus:
    enabled: true
    path: /modiapersonoversikt-api/internal/prometheus
  secureLogs:
    enabled: true
  resources:
    requests:
      cpu: 1000m
      memory: 4096Mi
    limits:
      cpu: 2000m
      memory: 8192Mi
  ingresses:
    - https://modiapersonoversikt-api-q0.nais.preprod.local
    - https://app-q0.adeo.no/modiapersonoversikt-api
    - https://modapp-q0.adeo.no/modiapersonoversikt-api
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 60
  vault:
    enabled: true
    paths:
      - kvPath: /serviceuser/data/dev/srvmodiabrukerdialog
        mountPath: /var/run/secrets/nais.io/service_user
      - kvPath: /serviceuser/data/dev/srvssolinux
        mountPath: /var/run/secrets/nais.io/srvssolinux
      - kvPath: /apikey/appdynamics/dev
        mountPath: /var/run/secrets/nais.io/vault
  leaderElection: true
  webproxy: true
  azure:
    application:
      enabled: true
      tenant: trygdeetaten.no
      allowAllUsers: true
      claims:
        extra:
          - "NAVident"
  accessPolicy:
    inbound:
      rules:
        - application: modiapersonoversikt-q0
          namespace: personoversikt
          cluster: dev-fss
  env:
    - name: APP_ENVIRONMENT_NAME
      value: "q0"
    - name: APP_VERSION
      value: "{{ version }}"
    - name: ONPREM_CLUSTER_NAME
      value: "dev-fss"
    - name: GCP_CLUSTER
      value: "dev-gcp"
    - name: SECURITY_TOKEN_SERVICE_DISCOVERY_URL
      value: "https://security-token-service.nais.preprod.local/rest/v1/sts/.well-known/openid-configuration"
    - name: SECURITYTOKENSERVICE_URL
      value: "https://security-token-service.nais.preprod.local/rest/v1/sts/ws/samltoken"
    - name: BRUKERVARSELV1_ENDPOINTURL
      value: "https://app-q0.adeo.no/varsel/ws/Brukervarsel/v1"
    - name: FELLES_KODEVERK_URL
      value: "https://kodeverk.nais.preprod.local"
    - name: LDAP_BASEDN
      value: "dc=preprod,dc=local"
    - name: LDAP_DOMAIN
      value: "PREPROD.LOCAL"
    - name: LDAP_SERVICEUSER_BASEDN
      value: "ou=ServiceAccounts,dc=preprod,dc=local"
    - name: LDAP_URL
      value: "ldaps://ldapgw.preprod.local"
    - name: LDAP_USER_BASEDN
      value: "ou=NAV,ou=BusinessUnits,dc=preprod,dc=local"
    - name: SAF_GRAPHQL_URL
      value: "https://saf-q0.nais.preprod.local/graphql"
    - name: SAF_HENTDOKUMENT_URL
      value: "https://saf-q0.nais.preprod.local/rest/hentdokument"
    - name: SAF_SCOPE
      value: "dev-fss:teamdokumenthandtering:saf-q0"
    - name: SAKOGBEHANDLING_ENDPOINTURL
      value: "https://modapp-q0.adeo.no/sakogbehandling/ws/SakOgBehandling_v1"
    - name: SERVER_DREK_URL
      value: "https://pdl-web.dev.intern.nav.no/rekvirerdnummer"
    - name: SERVER_NORG2_FRONTEND_URL
      value: "https://norg2-frontend.intern.dev.nav.no"
    - name: UNLEASH_API_URL
      value: "https://unleash.nais.io/api/"
    - name: REST_UTBETALING_ENDPOINTURL
      value: "https://sokos-utbetaldata.dev.intern.nav.no/utbetaldata/api"
    - name: UTBETALING_SCOPE
      value: "dev-fss:okonomi:sokos-utbetaldata"
    - name: VEILARBOPPFOLGINGAPI_URL
      value: "https://veilarboppfolging.dev.intern.nav.no/veilarboppfolging/api"
    - name: VEILARBOPPFOLGINGAPI_SCOPE
      value: "dev-fss:pto:veilarboppfolging"
    - name: KRR_REST_URL
      value: "https://digdir-krr-proxy.intern.dev.nav.no/"
    - name: KRR_SCOPE
      value: "dev-gcp:team-rocket:digdir-krr-proxy"
    - name: VIRKSOMHET_FORELDREPENGER_V2_ENDPOINTURL
      value: "https://modapp-q0.adeo.no/infotrygd-ws/ForeldrepengerService/v2"
    - name: VIRKSOMHET_OPPFOLGING_V1_ENDPOINTURL
      value: "https://arena-q0.adeo.no/ail_ws/Oppfoelging_v1"
    - name: EREG_ENDPOINTURL
      value: "https://modapp-q0.adeo.no/ereg/"
    - name: KONTOREGISTER_REST_URL
      value: "https://sokos-kontoregister-person.intern.dev.nav.no/kontoregister/api/kontoregister"
    - name: KONTOREGISTER_SCOPE
      value: "dev-gcp:okonomi:sokos-kontoregister-person"
    - name: VIRKSOMHET_PERSON_V3_ENDPOINTURL
      value: "https://app-q0.adeo.no/tpsws-aura/ws/Person/v3"
    - name: VIRKSOMHET_PERSONSOK_V1_ENDPOINTURL
      value: "https://app-q0.adeo.no/tpsws-aura/ws/Personsok/v1"
    - name: VIRKSOMHET_PLEIEPENGER_V1_ENDPOINTURL
      value: "https://modapp-q0.adeo.no/infotrygd-ws/Pleiepenger/v1"
    - name: VIRKSOMHET_SYKEPENGER_V2_ENDPOINTURL
      value: "https://modapp-q0.adeo.no/infotrygd-ws/SykepengerService/v2"
    - name: VIRKSOMHET_YTELSESKONTRAKT_V3_ENDPOINTURL
      value: "https://arena-q0.adeo.no/ail_ws/Ytelseskontrakt_v3"
    - name: SF_HENVENDELSE_URL
      value: "https://sf-henvendelse-api-proxy.dev.intern.nav.no/api"
    - name: SF_HENVENDELSE_SCOPE
      value: "dev-fss:teamnks:sf-henvendelse-api-proxy"
    - name: PDL_API_URL
      value: "https://pdl-api-q0.dev.intern.nav.no/graphql"
    - name: PDL_SCOPE
      value: "dev-fss:pdl:pdl-api"
    - name: PERSONFORVALTER_URL
      value: "https://pdl-web.dev.intern.nav.no/endreperson"
    - name: OPPGAVE_BASEURL
      value: "https://oppgave-q0.nais.preprod.local/"
    - name: OPPGAVE_SCOPE
      value: "dev-fss:oppgavehandtering:oppgave"
    - name: NORG2_BASEURL
      value: "https://app-q0.adeo.no/norg2"
    - name: SAKSOVERSIKT_PRODSETTNINGSDATO
      value: "2016-06-04"
    - name: INTERNAL_TILGANG
      value: "Z990351,Z994123,Z994404"
    - name: CXF_SECURE_LOG
      value: "enabled"
    - name: AXSYS_URL
      value: "https://axsys.dev.adeo.no"
    - name: AXSYS_SCOPE
      value: "dev-fss:org:axsys"
    - name: NOM_URL
      value: "https://nom-api.intern.dev.nav.no"
    - name: NOM_SCOPE
      value: "dev-gcp:nom:nom-api"
    - name: SKJERMEDE_PERSONER_PIP_URL
      value: "https://skjermede-personer-pip.intern.dev.nav.no"
    - name: SKJERMEDE_PERSONER_SCOPE
      value: "dev-gcp:nom:skjermede-personer-pip"
    - name: ARENA_SAK_VEDTAK_URL
      value: "https://arena-q0.adeo.no/arena_ws/services/ArenaSakVedtakService"
    - name: TMS_EVENT_API_URL
      value: "https://tms-event-api.ekstern.dev.nav.no/tms-event-api"
    - name: TMS_EVENT_API_SCOPE
      value: "dev-gcp:min-side:tms-event-api"