apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: modiapersonoversikt-api
  namespace: q1
  labels:
    team: personoversikt
spec:
  image: "{{image}}"
  port: 8080
  team: personoversikt
  liveness:
    path: /modiapersonoversikt-api/internal/isAlive
    initialDelay: 50
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /modiapersonoversikt-api/internal/isReady
    initialDelay: 50
    timeout: 1
  prometheus:
    enabled: true
    path: /modiapersonoversikt-api/internal/prometheus
  secureLogs:
    enabled: true
  resources:
    requests:
      cpu: 1000m
      memory: 4096Mi
    limits:
      cpu: 2000m
      memory: 8192Mi
  ingresses:
    - https://modiapersonoversikt-api-q1.nais.preprod.local
    - https://app-q1.adeo.no/modiapersonoversikt-api
    - https://modapp-q1.adeo.no/modiapersonoversikt-api
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 60
  vault:
    enabled: true
    paths:
      - kvPath: /serviceuser/data/dev/srvmodiabrukerdialog
        mountPath: /var/run/secrets/nais.io/service_user
      - kvPath: /serviceuser/data/dev/srvssolinux
        mountPath: /var/run/secrets/nais.io/srvssolinux
      - kvPath: /serviceuser/data/dev/srvgosys
        mountPath: /var/run/secrets/nais.io/gosys_user
      - kvPath: /apikey/appdynamics/dev
        mountPath: /var/run/secrets/nais.io/vault
  leaderElection: true
  env:
    - name: APP_ENVIRONMENT_NAME
      value: "q1"
    - name: APP_VERSION
      value: "{{ version }}"
    - name: MODIA_CLIENT_ID
      value: "modialogin-q1"
    - name: MODIA_REFRESH_URL
      value: "https://app-q1.adeo.no/modialogin/api/refresh"
    - name: ISSO_DISCOVERY_URL
      value: "https://isso-q.adeo.no/isso/oauth2/.well-known/openid-configuration"
    - name: SECURITY_TOKEN_SERVICE_DISCOVERY_URL
      value: "https://security-token-service.nais.preprod.local/rest/v1/sts/.well-known/openid-configuration"
    - name: SECURITYTOKENSERVICE_URL
      value: "https://sts-q1.preprod.local/SecurityTokenServiceProvider/"
    - name: ABAC_PDP_ENDPOINT_URL
      value: "https://abac-modia-q1.dev.intern.nav.no/application/authorize"
    - name: AKTOER_V1_ENDPOINTURL
      value: "https://app-q1.adeo.no/aktoerregister/ws/Aktoer/v1"
    - name: AKTOER_V2_ENDPOINTURL
      value: "https://app-q1.adeo.no/aktoerregister/ws/Aktoer/v2"
    - name: AKTOER_V1_SECURITYTOKEN
      value: "SAML"
    - name: AKTOER_V1_WSDLURL
      value: "http://maven.adeo.no/nexus/content/groups/public/no/nav/tjenester/fim/nav-fim-aktoer-v1-tjenestespesifikasjon/1.0.0/nav-fim-aktoer-v1-tjenestespesifikasjon-1.0.0.zip"
    - name: BRUKERVARSELV1_ENDPOINTURL
      value: "https://app-q1.adeo.no/varsel/ws/Brukervarsel/v1"
    - name: BRUKERVARSELV1_SECURITYTOKEN
      value: "SAML"
    - name: BRUKERVARSELV1_WSDLURL
      value: "http://maven.adeo.no/nexus/content/groups/public/no/nav/tjenester/nav-brukervarsel-v1-tjenestespesifikasjon/1.0.4/nav-brukervarsel-v1-tjenestespesifikasjon-1.0.4.zip"
    - name: DOMENE_BRUKERDIALOG_BEHANDLEHENVENDELSE_V1_ENDPOINTURL
      value: "https://modapp-q1.adeo.no/henvendelse/services/domene.Brukerdialog/BehandleHenvendelse_v1"
    - name: DOMENE_BRUKERDIALOG_BEHANDLEHENVENDELSE_V1_SECURITYTOKEN
      value: "SAML"
    - name: DOMENE_BRUKERDIALOG_BEHANDLEHENVENDELSE_V1_WSDLURL
      value: "http://maven.adeo.no/nexus/content/groups/public/no/nav/tjenestespesifikasjoner/behandle-henvendelse/1.2019.04.04-09.14-c6cea90b8e95/behandle-henvendelse-1.2019.04.04-09.14-c6cea90b8e95.zip"
    - name: DOMENE_BRUKERDIALOG_HENVENDELSE_V2_ENDPOINTURL
      value: "https://modapp-q1.adeo.no/henvendelse/services/domene.Brukerdialog/Henvendelse_v2"
    - name: DOMENE_BRUKERDIALOG_HENVENDELSE_V2_SECURITYTOKEN
      value: "SAML"
    - name: DOMENE_BRUKERDIALOG_HENVENDELSE_V2_WSDLURL
      value: "http://maven.adeo.no/nexus/content/groups/public/no/nav/sbl/dialogarena/henvendelse-informasjon-v2/0.6/henvendelse-informasjon-v2-0.6.zip"
    - name: DOMENE_BRUKERDIALOG_HENVENDELSESOKNADERSERVICE_V1_ENDPOINTURL
      value: "https://modapp-q1.adeo.no/henvendelse/services/domene.Brukerdialog/HenvendelseSoknaderService_v1"
    - name: DOMENE_BRUKERDIALOG_HENVENDELSESOKNADERSERVICE_V1_SECURITYTOKEN
      value: "SAML"
    - name: DOMENE_BRUKERDIALOG_HENVENDELSESOKNADERSERVICE_V1_WSDLURL
      value: "http://maven.adeo.no/nexus/content/groups/public/no/nav/sbl/dialogarena/henvendelse-soknader-tjenestespesifikasjon/0.0.26/henvendelse-soknader-tjenestespesifikasjon-0.0.26.zip"
    - name: DOMENE_BRUKERDIALOG_SENDUTHENVENDELSE_V1_ENDPOINTURL
      value: "https://modapp-q1.adeo.no/henvendelse/services/domene.Brukerdialog/SendUtHenvendelse_v1"
    - name: DOMENE_BRUKERDIALOG_SENDUTHENVENDELSE_V1_SECURITYTOKEN
      value: "SAML"
    - name: DOMENE_BRUKERDIALOG_SENDUTHENVENDELSE_V1_WSDLURL
      value: "http://maven.adeo.no/nexus/content/groups/public/no/nav/sbl/dialogarena/send-ut-henvendelse/0.7/send-ut-henvendelse-0.7.zip"
    - name: INNSYNJOURNAL_V2_ENDPOINTURL
      value: "https://dokarkiv-q1.nais.preprod.local/services/innsynjournal/v2"
    - name: INNSYNJOURNAL_V2_SECURITYTOKEN
      value: "SAML"
    - name: INNSYNJOURNAL_V2_WSDLURL
      value: "http://maven.adeo.no/nexus/content/groups/public/no/nav/tjenester/nav-innsynJournal-v2-tjenestespesifikasjon/2.0.2/nav-innsynJournal-v2-tjenestespesifikasjon-2.0.2.zip"
    - name: JOURNAL_V2_ENDPOINTURL
      value: "https://wasapp-q1.adeo.no/joark/Journal/v2"
    - name: JOURNAL_V2_SECURITYTOKEN
      value: "SAML"
    - name: JOURNAL_V2_WSDLURL
      value: "http://maven.adeo.no/nexus/content/groups/public/no/nav/tjenester/nav-journal-v2-tjenestespesifikasjon/1.0.3/nav-journal-v2-tjenestespesifikasjon-1.0.3.zip"
    - name: KODEVERKSMAPPER_OPPGAVETYPE_DESCRIPTION
      value: "Mapper fra oppgavetyper i fellessystemers kodeverk til oppgavetyper felles kodeverk"
    - name: KODEVERKSMAPPER_OPPGAVETYPE_URL
      value: "https://kodeverksmapper.nais.preprod.local/kodeverksmapper/mapOppgavetype"
    - name: KODEVERKSMAPPER_PING_DESCRIPTION
      value: "Ping-tjeneste som kan kalles fra konsumenters selftest"
    - name: KODEVERKSMAPPER_PING_URL
      value: "https://kodeverksmapper.nais.preprod.local/kodeverksmapper/ping"
    - name: KODEVERKSMAPPER_UNDERKATEGORI_DESCRIPTION
      value: "Mapper fra underkategorier i fellessystemers kodeverk til behandlingstema og behandlingstype i felles kodeverk"
    - name: KODEVERKSMAPPER_UNDERKATEGORI_URL
      value: "https://kodeverksmapper.nais.preprod.local/kodeverksmapper/mapUnderkategori"
    - name: FELLES_KODEVERK_URL
      value: "https://kodeverk.nais.preprod.local"
    - name: LDAP_BASEDN
      value: "dc=preprod,dc=local"
    - name: LDAP_DOMAIN
      value: "PREPROD.LOCAL"
    - name: LDAP_SERVICEUSER_BASEDN
      value: "ou=ServiceAccounts,dc=preprod,dc=local"
    - name: LDAP_URL
      value: "ldaps://ldapgw.preprod.local"
    - name: LDAP_USER_BASEDN
      value: "ou=NAV,ou=BusinessUnits,dc=preprod,dc=local"
    - name: MODIABRUKERDIALOG_STANDARDTEKSTER_TILBAKEMELDING_URL
      value: "https://navet.adeo.no/411275.cms"
    - name: PENSJON_PENSJONSAK_V1_ENDPOINTURL
      value: "https://pensjon-pen-q1.nais.preprod.local/pen/services/PensjonSak_v1"
    - name: PENSJON_PENSJONSAK_V1_SECURITYTOKEN
      value: "SAML"
    - name: PENSJON_PENSJONSAK_V1_WSDLURL
      value: "http://maven.adeo.no/nexus/content/groups/public/no/nav/tjenester/fim/nav-pensjonSak-v1-tjenestespesifikasjon/1.0.0/nav-pensjonSak-v1-tjenestespesifikasjon-1.0.0.zip"
    - name: SAF_GRAPHQL_URL
      value: "https://saf-q1.nais.preprod.local/graphql"
    - name: SAF_HENTDOKUMENT_URL
      value: "https://saf-q1.nais.preprod.local/rest/hentdokument"
    - name: SAKOGBEHANDLING_ENDPOINTURL
      value: "https://modapp-q1.adeo.no/sakogbehandling/ws/SakOgBehandling_v1"
    - name: SAKOGBEHANDLING_SECURITYTOKEN
      value: "SAML"
    - name: SAKOGBEHANDLING_WSDLURL
      value: "http://maven.adeo.no/nexus/content/groups/public/no/nav/tjenester/fim/nav-fim-sakOgBehandling-v1-tjenestespesifikasjon/1.0.0-alpha011/nav-fim-sakOgBehandling-v1-tjenestespesifikasjon-1.0.0-alpha011.zip"
    - name: SERVER_AKTIVITETSPLAN_URL
      value: "https://app-q1.adeo.no"
    - name: SERVER_ARENA_URL
      value: "http://arena-q1.adeo.no/forms/arenaMod_q1.html"
    - name: SERVER_DREK_URL
      value: "https://drek.nais.preprod.local/"
    - name: SERVER_GOSYS_URL
      value: "https://wasapp-q1.adeo.no"
    - name: SERVER_NORG2_FRONTEND_URL
      value: "https://norg2-frontend.nais.preprod.local"
    - name: SERVER_PESYS_URL
      value: "https://wasapp-q1.adeo.no"
    - name: SERVER_VEILARBPORTEFOLJEFLATEFS_URL
      value: "https://app-q1.adeo.no/veilarbportefoljeflatefs"
    - name: SERVER_AAREG_URL
      value: "https://modapp-q1.adeo.no/aareg-web"
    - name: TJENESTEBUSS_URL
      value: "https://tjenestebuss-q1.adeo.no/"
    - name: TJENESTER_URL
      value: "https://tjenester-q1.nav.no"
    - name: UNLEASH_API_URL
      value: "https://unleash.nais.io/api/"
    - name: UTBETALING_V1_DESCRIPTION
      value: "Utbetalingsoversikt"
    - name: UTBETALING_V1_ENDPOINTURL
      value: "https://wasapp-q1.adeo.no/nav-utbetaldata-ws/virksomhet/Utbetaling_v1"
    - name: UTBETALING_V1_SECURITYTOKEN
      value: "SAML"
    - name: UTBETALING_V1_WSDLURL
      value: "http://maven.adeo.no/nexus/content/groups/public/no/nav/tjenester/fim/nav-fim-utbetaling-v1-tjenestespesifikasjon/1.1.3/nav-fim-utbetaling-v1-tjenestespesifikasjon-1.1.3.zip"
    - name: VEILARBOPPFOLGINGAPI_URL
      value: "https://veilarboppfolging-q1.nais.preprod.local/veilarboppfolging/api"
    #    - name: VIRKSOMHET_ARBEIDOGAKTIVITET_V1_ENDPOINTURL
    #      value: "https\://tjenestebuss-q1.adeo.no/nav-tjeneste-arbeidOgAktivitet_v1Web/sca/ArbeidOgAktivitetWSEXP"
    - name: VIRKSOMHET_ARBEIDOGAKTIVITET_V1_ENDPOINTURL
      value: "https://service-gw-q1.preprod.local/"
    - name: VIRKSOMHET_ARBEIDOGAKTIVITET_V1_SECURITYTOKEN
      value: "LTPA"
    - name: VIRKSOMHET_ARBEIDOGAKTIVITET_V1_WSDLURL
      value: "http://maven.adeo.no/nexus/service/local/artifact/maven/redirect?r=m2internal&g=no.nav.esb.nav&a=nav-tjeneste-arbeidOgAktivitet&v=1.0.6&e=zip&c=wsdlif"
    - name: VIRKSOMHET_ARBEIDSFORDELING_V1_ENDPOINTURL
      value: "https://app-q1.adeo.no/norg2/ws/Arbeidsfordeling/v1"
    - name: VIRKSOMHET_ARBEIDSFORDELING_V1_SECURITYTOKEN
      value: "SAML"
    - name: VIRKSOMHET_ARBEIDSFORDELING_V1_WSDLURL
      value: "http://maven.adeo.no/nexus/content/groups/public/no/nav/tjenester/nav-arbeidsfordeling-v1-tjenestespesifikasjon/1.1.0/nav-arbeidsfordeling-v1-tjenestespesifikasjon-1.1.0.zip"
    - name: VIRKSOMHET_DIGITALKONTAKINFORMASJON_V1_ENDPOINTURL
      value: "https://dkif.nais.preprod.local/ws/DigitalKontaktinformasjon/v1"
    - name: DKIF_REST_URL
      value: "https://dkif.dev.adeo.no/"
    - name: VIRKSOMHET_DIGITALKONTAKINFORMASJON_V1_SECURITYTOKEN
      value: "SAML"
    - name: VIRKSOMHET_DIGITALKONTAKINFORMASJON_V1_WSDLURL
      value: "http://maven.adeo.no/nexus/service/local/artifact/maven/redirect?a=nav-digitalKontaktinformasjon-v1-tjenestespesifikasjon&e=zip&g=no.nav.tjenester.fim&r=m2internal&v=2.0.0"
    - name: VIRKSOMHET_EGENANSATT_V1_ENDPOINTURL
      value: "https://app-q1.adeo.no/tpsws-aura/ws/EgenAnsatt/v1"
    - name: VIRKSOMHET_EGENANSATT_V1_SECURITYTOKEN
      value: "SAML"
    - name: VIRKSOMHET_EGENANSATT_V1_WSDLURL
      value: "http://maven.adeo.no/nexus/content/groups/public/no/nav/tjenester/pip/nav-pip-egenAnsatt-v1-tjenestespesifikasjon/1.0.1/nav-pip-egenAnsatt-v1-tjenestespesifikasjon-1.0.1.zip"
    - name: VIRKSOMHET_FORELDREPENGER_V2_ENDPOINTURL
      value: "https://modapp-q1.adeo.no/infotrygd-ws/ForeldrepengerService/v2"
    - name: VIRKSOMHET_FORELDREPENGER_V2_SECURITYTOKEN
      value: "SAML"
    - name: VIRKSOMHET_FORELDREPENGER_V2_WSDLURL
      value: "http://maven.adeo.no/nexus/content/groups/public/no/nav/tjenester/nav-foreldrepenger-v2-tjenestespesifikasjon/2.0.2/nav-foreldrepenger-v2-tjenestespesifikasjon-2.0.2.zip"
    - name: VIRKSOMHET_KODEVERK_V2_ENDPOINTURL
      value: "https://kodeverk.nais.preprod.local/ws/kodeverk/v2"
    - name: VIRKSOMHET_KODEVERK_V2_SECURITYTOKEN
      value: "NONE"
    - name: VIRKSOMHET_KODEVERK_V2_WSDLURL
      value: "http://maven.adeo.no/nexus/content/groups/public/no/nav/tjenester/fim/nav-fim-kodeverk-v2-tjenestespesifikasjon/2.0.0/nav-fim-kodeverk-v2-tjenestespesifikasjon-2.0.0.zip"
    - name: VIRKSOMHET_OPPFOLGING_V1_ENDPOINTURL
      value: "https://arena-q1.adeo.no/ail_ws/Oppfoelging_v1"
    - name: VIRKSOMHET_OPPFOLGING_V1_SECURITYTOKEN
      value: "SAML"
    - name: VIRKSOMHET_OPPFOLGING_V1_WSDLURL
      value: "http://maven.adeo.no/nexus/content/repositories/public/no/nav/tjenester/fim/nav-fim-oppfoelging-v1-tjenestespesifikasjon/1.2.0/nav-fim-oppfoelging-v1-tjenestespesifikasjon-1.2.0.zip"
    - name: EREG_ENDPOINTURL
      value: "https://modapp-q1.adeo.no/ereg/"
    - name: VIRKSOMHET_ORGANISASJONENHET_V2_ENDPOINTURL
      value: "https://app-q1.adeo.no/norg2/ws/OrganisasjonEnhet/v2"
    - name: VIRKSOMHET_ORGANISASJONENHET_V2_SECURITYTOKEN
      value: "SAML"
    - name: VIRKSOMHET_ORGANISASJONENHET_V2_WSDLURL
      value: "http://maven.adeo.no/nexus/content/groups/public/no/nav/tjenester/nav-organisasjonEnhet-v2-tjenestespesifikasjon/2.1.0/nav-organisasjonEnhet-v2-tjenestespesifikasjon-2.1.0.zip"
    - name: VIRKSOMHET_ORGANISASJONENHETKONTAKTINFORMASJON_V1_ENDPOINTURL
      value: "https://app-q1.adeo.no/norg2/ws/OrganisasjonEnhetKontaktinformasjon/v1"
    - name: VIRKSOMHET_ORGANISASJONENHETKONTAKTINFORMASJON_V1_SECURITYTOKEN
      value: "SAML"
    - name: VIRKSOMHET_ORGANISASJONENHETKONTAKTINFORMASJON_V1_WSDLURL
      value: "http://maven.adeo.no/nexus/content/groups/public/no/nav/tjenester/nav-organisasjonEnhetKontaktinformasjon-v1-tjenestespesifikasjon/1.1.0/nav-organisasjonEnhetKontaktinformasjon-v1-tjenestespesifikasjon-1.1.0.zip"
    - name: VIRKSOMHET_PERSON_V3_ENDPOINTURL
      value: "https://app-q1.adeo.no/tpsws-aura/ws/Person/v3"
    - name: VIRKSOMHET_PERSON_V3_SECURITYTOKEN
      value: "SAML"
    - name: VIRKSOMHET_PERSON_V3_WSDLURL
      value: "http://maven.adeo.no/nexus/content/groups/public/no/nav/tjenester/nav-person-v3-tjenestespesifikasjon/3.6.1/nav-person-v3-tjenestespesifikasjon-3.6.1.zip"
    - name: VIRKSOMHET_PERSONSOK_V1_ENDPOINTURL
      value: "https://app-q1.adeo.no/tpsws-aura/ws/Personsok/v1"
    - name: VIRKSOMHET_PERSONSOK_V1_SECURITYTOKEN
      value: "SAML"
    - name: VIRKSOMHET_PERSONSOK_V1_WSDLURL
      value: "http://maven.adeo.no/nexus/content/groups/public/no/nav/tjenester/fim/nav-fim-personsok-v1-tjenestespesifikasjon/1.0.1/nav-fim-personsok-v1-tjenestespesifikasjon-1.0.1.zip"
    - name: VIRKSOMHET_PLEIEPENGER_V1_ENDPOINTURL
      value: "https://modapp-q1.adeo.no/infotrygd-ws/Pleiepenger/v1"
    - name: VIRKSOMHET_PLEIEPENGER_V1_SECURITYTOKEN
      value: "SAML"
    - name: VIRKSOMHET_PLEIEPENGER_V1_WSDLURL
      value: "http://maven.adeo.no/nexus/content/groups/public/no/nav/tjenester/nav-pleiepenger-v1-tjenestespesifikasjon/1.0.4/nav-pleiepenger-v1-tjenestespesifikasjon-1.0.4.zip"
    - name: SAK_ENDPOINTURL
      value: "https://sak.nais.preprod.local"
    - name: VIRKSOMHET_SYKEPENGER_V2_ENDPOINTURL
      value: "https://modapp-q1.adeo.no/infotrygd-ws/SykepengerService/v2"
    - name: VIRKSOMHET_SYKEPENGER_V2_SECURITYTOKEN
      value: "SAML"
    - name: VIRKSOMHET_SYKEPENGER_V2_WSDLURL
      value: "http://maven.adeo.no/nexus/content/groups/public/no/nav/tjenester/nav-sykepenger-v2-tjenestespesifikasjon/2.0.1/nav-sykepenger-v2-tjenestespesifikasjon-2.0.1.zip"
    - name: VIRKSOMHET_YTELSESKONTRAKT_V3_ENDPOINTURL
      value: "https://arena-q1.adeo.no/ail_ws/Ytelseskontrakt_v3"
    - name: VIRKSOMHET_YTELSESKONTRAKT_V3_SECURITYTOKEN
      value: "SAML"
    - name: VIRKSOMHET_YTELSESKONTRAKT_V3_WSDLURL
      value: "http://maven.adeo.no/nexus/content/groups/public/no/nav/tjenester/fim/nav-fim-ytelseskontrakt-v3-tjenestespesifikasjon/3.0.1/nav-fim-ytelseskontrakt-v3-tjenestespesifikasjon-3.0.1.zip"
    - name: HENVENDELSE_LES_API_URL
      value: "https://modapp-q1.adeo.no/henvendelse-les/api"
    - name: SF_HENVENDELSE_URL
      value: "https://sf-henvendelse.dev.intern.nav.no/api"
    - name: PDL_API_URL
      value: "https://pdl-api-q1.dev.intern.nav.no/graphql"
    - name: PERSONFORVALTER_URL
      value: "https://pdl-web.dev.intern.nav.no/endreperson"
    - name: OPPGAVE_BASEURL
      value: "https://oppgave.nais.preprod.local/"
    - name: BISYS_BASEURL
      value: "https://bidrag-sak.dev.adeo.no/bidrag-sak"
    - name: TILLATMOCK
      value: "true"
    - name: VISUTBETALINGER
      value: "true"
    - name: DEAKTIVERAAREGLENKE
      value: "false"
    - name: PREFETCH_NORG_ANSATTLISTE_SCHEDULE
      value: "0 0 7,19 * * *"
    - name: UTBETALINGTILGANG
      value: "[]"
    - name: TEMASIDER_VIKTIGAVITELENKE
      value: "DAG,AAP,IND"
    - name: BEHANDLINGSSTATUS_SYNLIG_ANTALLDAGER
      value: "28"
    - name: SAKSOVERSIKT_PRODSETTNINGSDATO
      value: "2016-06-04"
    - name: FJERN_SOKNADER_FOR_DATO
      value: "2014-12-09"
    - name: TOGGLE_DIGISYFO
      value: "true"
    - name: VISNYEKOER
      value: "true"
    - name: VISDELVISESVARFUNKSJONALITET
      value: "true"
    - name: VISPLEIEPENGER
      value: "true"
    - name: ORGENHET_2_1
      value: "true"
    - name: VISENDRENAVNFUNKSJONALITET
      value: "true"
    - name: VISORGANISASJONENHETKONTAKTINFORMASJON
      value: "true"
    - name: FEATURE_AKTIVERPERSONRESTAPI
      value: "true"
    - name: FEATURE_NYTTVISITTKORT
      value: "true"
    - name: HASTEKASSERING_TILGANG
      value: "Z992323,Z990366,Z990083,Z990351"
    - name: CXF_SECURE_LOG
      value: "enabled"
