openapi: "3.1.0"
info:
  title: "tiltakspenger_datadeling API"
  description: "tiltakspenger_datadeling API"
  version: "1.0.0"
servers:
  - url: "https://tiltakspenger_datadeling"
security:
  - Authorization: []
paths:
  /behandling:
    post:
      description: ""
      responses:
        "400":
          description: "Bad Request"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ErrorJson"
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "object"
  /behandlinger/perioder:
    post:
      tags:
        - Tiltakspenger
      description: ""
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/VedtakReqDTO"
        required: true
      responses:
        "400":
          description: "Bad Request"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/MappingError"
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BehandlingPerioderResponse"
  /isalive:
    get:
      tags:
        - Tiltakspenger
      description: ""
      responses:
        "200":
          description: "OK"
          content:
            text/plain:
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "ALIVE"
  /isready:
    get:
      tags:
        - Tiltakspenger
      description: ""
      responses:
        "200":
          description: "OK"
          content:
            text/plain:
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "READY"
        "503":
          description: "Service Unavailable"
          content:
            text/plain:
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "NOT READY"
  /vedtak:
    post:
      description: ""
      responses:
        "400":
          description: "Bad Request"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ErrorJson"
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "object"
  /vedtak/detaljer:
    post:
      tags:
        - Tiltakspenger
      description: ""
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/VedtakReqDTO"
        required: true
      responses:
        "400":
          description: "Bad Request"
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/VedtakDetaljer"
  /vedtak/perioder:
    post:
      tags:
        - Tiltakspenger
      description: ""
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/VedtakReqDTO"
        required: true
      responses:
        "400":
          description: "Bad Request"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/MappingError"
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/VedtakPerioderResponse"
components:
  schemas:
    ErrorJson:
      type: "object"
      properties:
        melding:
          type: "string"
        kode:
          type: "string"
      required:
        - "melding"
        - "kode"
    VedtakReqDTO:
      type: "object"
      properties:
        ident:
          type: "string"
        fom:
          type: "string"
        tom:
          type: "string"
    VedtakDetaljer:
      type: "array"
      items:
        type: "object"
        properties:
          fom:
            type: "string"
            format: "date"
            description: "The start date in YYYY-MM-DD format"
          tom:
            type: "string"
            format: "date"
            description: "The end date in YYYY-MM-DD format"
          antallDager:
            type: "number"
            description: "The number of days"
          dagsatsTiltakspenger:
            type: "integer"
            description: "The daily rate for tiltakspenger"
          dagsatsBarnetillegg:
            type: "integer"
            description: "The daily rate for barnetillegg"
          antallBarn:
            type: "integer"
            description: "The number of children"
          relaterteTiltak:
            type: "string"
            description: "Related measures"
          rettighet:
            type: "string"
            enum:
              - TILTAKSPENGER
              - BARNETILLEGG
              - TILTAKSPENGER_OG_BARNETILLEGG
              - INGENTING
            description: "The right associated with the vedtak"
          vedtakId:
            type: "string"
            description: "The ID of the vedtak"
          sakId:
            type: "string"
            description: "The ID of the case"
          saksnummer:
            type: "string"
            description: "The case number"
          kilde:
            type: "string"
            description: "The source of the vedtak"
        required: [ "fom", "tom", "antallDager", "dagsatsTiltakspenger", "dagsatsBarnetillegg", "antallBarn", "relaterteTiltak", "rettighet", "vedtakId", "sakId", "saksnummer", "kilde" ]
    VedtakPerioderResponse:
      type: array
      items:
        type: object
        properties:
          vedtakId:
            type: string
            description: 'Id for vedtaket, enten fra arena eller tpsak'
          rettighet:
            type: string
            enum:
              - TILTAKSPENGER
              - TILTAKSPENGER_OG_BARNETILLEGG
            description: Rettigheten fra vedtaket
          periode:
            $ref: '#/components/schemas/Periode'
          kilde:
            type: string
            enum:
              - TPSAK
              - ARENA
            description: Kilden for vedtaket
          barnetillegg:
            type: object
            properties:
              perioder:
                type: array
                items:
                  $ref: '#/components/schemas/Barnetilleggperiode'
        required:
          - vedtakId
          - rettighet
          - periode
          - kilde
    Periode:
      type: object
      required:
        - fraOgMed
        - tilOgMed
      properties:
        fraOgMed:
          type: string
          format: date
          description: Startdato på format YYYY-MM-DD
        tilOgMed:
          type: string
          format: date
          description: Sluttdato på format YYYY-MM-DD
    Barnetilleggperiode:
      type: object
      required:
        - antallBarn
        - periode
      properties:
        antallBarn:
          type: integer
          description: Antall barn
        periode:
          $ref: '#/components/schemas/Periode'
    BehandlingPerioderResponse:
      type: array
      items:
        type: object
        properties:
          behandlingId:
            type: string
            description: 'The ID of the behandling. Ulid, prefixed with ''beh_'''
          fom:
            type: string
            format: date
            description: The start date in YYYY-MM-DD format
          tom:
            type: string
            format: date
            description: The end date in YYYY-MM-DD format
        required:
          - behandlingId
          - fom
          - tom
    MappingError:
      type: "object"
      properties:
        feilmelding:
          type: "string"
      required:
        - "feilmelding"