apiVersion: unleash.nais.io/v1
kind: ApiToken
metadata:
  name: modiapersonoversikt-api
  namespace: personoversikt
  labels:
    team: personoversikt
spec:
  unleashInstance:
    apiVersion: unleash.nais.io/v1
    kind: RemoteUnleash
    name: personoversikt
  secretName: modiapersonoversikt-api-unleash-api-token

  # Specify which environment the API token should be created for.
  # Can be one of: development, or production.
  environment: production

