package no.nav.modiapersonoversikt.integration.abac

interface AbacAttributeId {
    fun getId(): String
}

enum class NavAttributes(val attributeId: String) : AbacAttributeId {
    ADVICEOROBLIGATION_CAUSE("no.nav.abac.attributter.adviceorobligation.cause"),
    ADVICEOROBLIGATION_DENY_POLICY("no.nav.abac.attributter.adviceorobligation.deny_policy"),
    ADVICEOROBLIGATION_DENY_RULE("no.nav.abac.attributter.adviceorobligation.deny_rule"),
    ADVICEOROBLIGATION_FRITEKST("no.nav.abac.attributter.adviceorobligation.fritekst"),
    ADVICE_DENY_REASON("no.nav.abac.advices.reason.deny_reason"),
    ENVIRONMENT_FELLES_MILJOE("no.nav.abac.attributter.environment.felles.miljoe"),
    ENVIRONMENT_FELLES_OIDC_TOKEN_BODY("no.nav.abac.attributter.environment.felles.oidc_token_body"),
    ENVIRONMENT_FELLES_PEP_ID("no.nav.abac.attributter.environment.felles.pep_id"),
    ENVIRONMENT_FELLES_SAML_TOKEN("no.nav.abac.attributter.environment.felles.saml_token"),
    ENVIRONMENT_FELLES_TJENESTENAVN("no.nav.abac.attributter.environment.felles.tjenestenavn"),
    FORELDREPENGER_SAKLISTE("no.nav.abac.attributter.foreldrepenger.sakliste"),
    RESOURCE_ARENA_ARBEIDSSOEKER("no.nav.abac.attributter.resource.arena.arbeidssoeker"),
    RESOURCE_ARENA_OPPFOELGINGSKONTRAKTLISTE("no.nav.abac.attributter.resource.arena.oppfoelgingskontraktListe"),
    RESOURCE_ARENA_OPPFOELGINGSSTATUS("no.nav.abac.attributter.resource.arena.oppfoelgingsstatus"),
    RESOURCE_ARENA_STILLING("no.nav.abac.attributter.resource.arena.stilling"),
    RESOURCE_ARENA_VEDTAK("no.nav.abac.attributter.resource.arena.vedtak"),
    RESOURCE_ARENA_VEDTAKLISTE("no.nav.abac.attributter.resource.arena.vedtakliste"),
    RESOURCE_ARENA_YTELSEVEDTAK("no.nav.abac.attributter.resource.arena.ytelsevedtak"),
    RESOURCE_ARKIV_DOKUMENT("no.nav.abac.attributter.resource.arkiv.dokument"),
    RESOURCE_ARKIV_GSAK_SAKSID("no.nav.abac.attributter.resource.arkiv.gsak_saksid"),
    RESOURCE_ARKIV_JOURNALPOST("no.nav.abac.attributter.resource.arkiv.journalpost"),
    RESOURCE_ARKIV_PENSJON_SAKSID("no.nav.abac.attributter.resource.arkiv.pensjon_saksid"),
    RESOURCE_ARKIV_SAK("no.nav.abac.attributter.resource.arkiv.sak"),
    RESOURCE_DISTRIBUSJON_VARSEL_OM_OPPGAVE_TIL_BORGER("no.nav.abac.attributter.resource.distribusjon.varsel_om_oppgave_til_borger"),
    RESOURCE_DOKUMENTPRODUKSJON_DOKUMENT("no.nav.abac.attributter.resource.dokumentproduksjon.dokument"),
    RESOURCE_FELLES_DOMENE("no.nav.abac.attributter.resource.felles.domene"),
    RESOURCE_FELLES_ENHET("no.nav.abac.attributter.resource.felles.enhet"),
    RESOURCE_FELLES_PERSON("no.nav.abac.attributter.resource.felles.person"),
    RESOURCE_FELLES_PERSON_AKTOERID_RESOURCE("no.nav.abac.attributter.resource.felles.person.aktoerId_resource"),
    RESOURCE_FELLES_PERSON_EGEN_ANSATT("no.nav.abac.attributter.resource.felles.person.egen_ansatt"),
    RESOURCE_FELLES_PERSON_FNR("no.nav.abac.attributter.resource.felles.person.fnr"),
    RESOURCE_FELLES_PERSON_GEOGRAFISK_TILKNYTNING("no.nav.abac.attributter.resource.felles.person.geografisk_tilknytning"),
    RESOURCE_FELLES_PERSON_KONTAKTINFORMASJON("no.nav.abac.attributter.resource.felles.person.kontaktinformasjon"),
    RESOURCE_FELLES_PERSON_NAV_ENHET_ID("no.nav.abac.attributter.resource.felles.person.nav_enhet_id"),
    RESOURCE_FELLES_PERSON_NAVN("no.nav.abac.attributter.resource.felles.person.navn"),
    RESOURCE_FELLES_PERSON_RELASJON("no.nav.abac.attributter.resource.felles.person.relasjon"),
    RESOURCE_FELLES_PERSON_RELASJONER("no.nav.abac.attributter.resource.felles.person.relasjoner"),
    RESOURCE_FELLES_PERSON_SPESREG("no.nav.abac.attributter.resource.felles.person.spesreg"),
    RESOURCE_FELLES_PERSON_TILKNYTTET_EGEN_ANSATT("no.nav.abac.attributter.resource.felles.person.tilknyttet_egen_ansatt"),
    RESOURCE_FELLES_PERSON_TILKNYTTET_FNR("no.nav.abac.attributter.resource.felles.person.tilknyttet_fnr"),
    RESOURCE_FELLES_PERSON_TILKNYTTET_SPESREG("no.nav.abac.attributter.resource.felles.person.tilknyttet_spesreg"),
    RESOURCE_FELLES_RESOURCE_TYPE("no.nav.abac.attributter.resource.felles.resource_type"),
    RESOURCE_FELLES_TEMA("no.nav.abac.attributter.resource.felles.tema"),
    RESOURCE_FORELDREPENGER_SAK_AKSJONSPUNKT_TYPE("no.nav.abac.attributter.resource.foreldrepenger.sak.aksjonspunkt_type"),
    RESOURCE_FORELDREPENGER_SAK_ANSVARLIG_SAKSBEHANDLER("no.nav.abac.attributter.resource.foreldrepenger.sak.ansvarlig_saksbehandler"),
    RESOURCE_FORELDREPENGER_SAK_BEHANDLINGSSTATUS("no.nav.abac.attributter.resource.foreldrepenger.sak.behandlingsstatus"),
    RESOURCE_FORELDREPENGER_SAK_SAKSSTATUS("no.nav.abac.attributter.resource.foreldrepenger.sak.saksstatus"),
    RESOURCE_MODIA("no.nav.abac.attributter.resource.modia"),
    RESOURCE_NAVPERSON_ENDRINGSSOEKNAD("no.nav.abac.attributter.resource.navperson.endringssoeknad"),
    RESOURCE_NAVPERSON_PERSON_ENDRING("no.nav.abac.attributter.resource.navperson.person_endring"),
    RESOURCE_NAVPERSON_STATUS("no.nav.abac.attributter.resource.navperson.status"),
    RESOURCE_OPPGAVE_OPPGAVE("no.nav.abac.attributter.resource.oppgave.oppgave"),
    RESOURCE_OPPGAVE_OPPGAVETYPE("no.nav.abac.attributter.resource.oppgave.oppgavetype"),
    RESOURCE_PENSJON_PERSON_PENSJONSTATUS("no.nav.abac.attributter.resource.pensjon.person.pensjonstatus"),
    RESOURCE_PENSJON_PERSON_UFOREHISTORIKK("no.nav.abac.attributter.resource.pensjon.person.uforehistorikk"),
    RESOURCE_REGISTRE_FILTER("no.nav.abac.attributter.resource.registre.filter"),
    RESOURCE_REGISTRE_FULLMAKTSMOTTAKERELISTE("no.nav.abac.attributter.resource.registre.fullmaktsmottakereliste"),
    RESOURCE_REGISTRE_MEDLEMSKAP("no.nav.abac.attributter.resource.registre.medlemskap"),
    RESOURCE_REGISTRE_PERSON_SIKKERHETSTILTAK("no.nav.abac.attributter.resource.registre.person.sikkerhetstiltak"),
    RESOURCE_REGISTRE_PERSON_TPS_EGEN_ANSATT("no.nav.abac.attributter.resource.registre.person.tps_egen_ansatt"),
    RESOURCE_REGISTRE_PERSON_TPS_SPESREG("no.nav.abac.attributter.resource.registre.person.tps_spesreg"),
    RESOURCE_REGISTRE_PERSON_UTENLANDSK_IDENT("no.nav.abac.attributter.resource.registre.person.utenlandsk_ident"),
    RESOURCE_SAK_SAK("no.nav.abac.attributter.resource.sak.sak"),
    RESOURCE_SYFO_DIALOGMELDING("no.nav.abac.attributter.resource.syfo.dialogmelding"),
    RESOURCE_VEILARB("no.nav.abac.attributter.resource.veilarb"),
    RESOURCE_VEILARB_ENHET_EIENDEL("no.nav.abac.attributter.resource.veilarb.enhet.eiendel"),
    RESOURCE_VEILARB_KONTOR_LAAS("no.nav.abac.attributter.resource.veilarb.kontor_laas"),
    RESOURCE_VEILARB_OPPFOELGINGSENHET("no.nav.abac.attributter.resource.veilarb.oppfoelgingsenhet"),
    RESOURCE_VEILARB_PERSON("no.nav.abac.attributter.resource.veilarb.person"),
    RESOURCE_VEILARB_UNDER_OPPFOLGING("no.nav.abac.attributter.resource.veilarb.under_oppfoelging"),
    SUBJECT_FELLES_AKTOERID_SUBJECT("no.nav.abac.attributter.subject.felles.aktoerId_subject"),
    SUBJECT_FELLES_ALDER("no.nav.abac.attributter.subject.felles.alder"),
    SUBJECT_FELLES_AUTHENTICATIONLEVEL("no.nav.abac.attributter.subject.felles.authenticationLevel"),
    SUBJECT_FELLES_CONSUMERID("no.nav.abac.attributter.subject.felles.consumerId"),
    SUBJECT_FELLES_CONSUMERID_ROLLE("no.nav.abac.attributter.subject.felles.consumerId_rolle"),
    SUBJECT_FELLES_ENHETIDLISTE("no.nav.abac.attributter.subject.felles.enhetidliste"),
    SUBJECT_FELLES_ER_LEVENDE("no.nav.abac.attributter.subject.felles.er_levende"),
    SUBJECT_FELLES_HAR_TILGANG_EGEN_ANSATT("no.nav.abac.attributter.subject.felles.har_tilgang_egen_ansatt"),
    SUBJECT_FELLES_HAR_TILGANG_KODE_6("no.nav.abac.attributter.subject.felles.har_tilgang_kode_6"),
    SUBJECT_FELLES_HAR_TILGANG_KODE_7("no.nav.abac.attributter.subject.felles.har_tilgang_kode_7"),
    SUBJECT_FELLES_INDIREKTE_GRUPPER("no.nav.abac.attributter.subject.felles.indirekte_grupper"),
    SUBJECT_FELLES_SUBJECTTYPE("no.nav.abac.attributter.subject.felles.subjectType"),
    SUBJECT_REGISTRE_TPS_ALDER("no.nav.abac.attributter.subject.registre.tps_alder"),
    SUBJECT_REGISTRE_TPS_ER_LEVENDE("no.nav.abac.attributter.subject.registre.tps_er_levende");

    override fun getId(): String = this.attributeId
}
enum class StandardAttributter(val attributeId: String) : AbacAttributeId {
    SUBJECT_ID("urn:oasis:names:tc:xacml:1.0:subject:subject-id"),
    SUBJECT_ID_QUALIFIER("urn:oasis:names:tc:xacml:1.0:subject:subject-id-qualifier"),
    ROLE("urn:oasis:names:tc:xacml:2.0:subject:role"),
    KEY_INFO("urn:oasis:names:tc:xacml:1.0:subject:key-info"),
    AUTH_TIME("urn:oasis:names:tc:xacml:1.0:subject:authentication-time"),
    AUTH_METHOD("urn:oasis:names:tc:xacml:1.0:subject:authentication-method"),
    REQUEST_TIME("urn:oasis:names:tc:xacml:1.0:subject:request-time"),
    SESSION_START_TIME("urn:oasis:names:tc:xacml:1.0:subject:session-start-time"),
    LOCATION_IP("urn:oasis:names:tc:xacml:3.0:subject:authn-locality:ip-address"),
    LOCATION_DNS_NAME("urn:oasis:names:tc:xacml:3.0:subject:authn-locality:dns-name"),
    RESOURCE_ID("urn:oasis:names:tc:xacml:1.0:resource:resource-id"),
    ACTION_ID("urn:oasis:names:tc:xacml:1.0:action:action-id"),
    IMPLIED_ACTION("urn:oasis:names:tc:xacml:1.0:action:implied-action"),
    ACTION_NAMESPACE("urn:oasis:names:tc:xacml:1.0:action:action-namespace"),
    CURRENT_TIME("urn:oasis:names:tc:xacml:1.0:environment:current-time"),
    CURRENT_DATE("urn:oasis:names:tc:xacml:1.0:environment:current-date"),
    CURRENT_DATETIME("urn:oasis:names:tc:xacml:1.0:environment:current-dateTime");

    override fun getId(): String = this.attributeId
}
