package no.nav.sbl.dialogarena.modiabrukerdialog.api.domain.henvendelse;

public enum Meldingstype {
    DOKUMENT_VARSEL,
    OPPGAVE_VARSEL,
    SPORSMAL_SKRIFTLIG,
    SPORSMAL_SKRIFTLIG_DIREKTE,
    SVAR_SKRIFTLIG,
    SVAR_OPPMOTE,
    SVAR_TELEFON,
    DELVIS_SVAR_SKRIFTLIG,
    SAMTALEREFERAT_OPPMOTE,
    SAMTALEREFERAT_TELEFON,
    SPORSMAL_MODIA_UTGAAENDE,
    SVAR_SBL_INNGAAENDE
}
