export const API_BASE_URL = '/modiabrukerdialog/rest';

export const UKEDAGER = ['MANDAG', 'TIRSDAG', 'ONSDAG', 'TORSDAG', 'FREDAG', 'LORDAG', 'SONDAG'];

export const endash = '\u2013';

export const ADRESSETYPER = {
    GATEADRESSE: 'GATEADRESSE',
    MATRIKKELADRESSE: 'MATRIKKELADRESSE',
    INGEN_ADRESSE_REGISTRERT: 'INGEN_ADRESSE_REGISTRERT',
    USTRUKTURERT: 'USTRUKTURERT'
};
