version: 2.1
orbs:
  pus: navikt/pus-orb@0.0.41
jobs:
  dependency-plugin-hack:
    docker:
      - image: navikt/pus-pipeline
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ .Branch }}-{{ checksum "pom.xml" }}
      - run: mvn -B -P circleci install -DskipTests
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ .Branch }}-{{ checksum "pom.xml" }}
workflows:
  version: 2
  commit:
    jobs:
      - dependency-plugin-hack:
          context: pus
      - pus/test-backend:
          context: pus
          filters:
            branches:
              ignore:
                - master
                - dev
      - pus/bygg-og-deploy-backend:
          context: pus
          filepath: ./deploy/naiserator-q0.yaml
          filters:
            branches:
              only: dev
      - pus/bygg-og-deploy-backend:
          context: pus
          filepath: ./deploy/naiserator.yaml
          filters:
            branches:
              only: master