apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: modiapersonoversikt-api
  {{#if namespace}}
  namespace: {{namespace}}
  {{else}}
  namespace: default
  {{/if}}
  labels:
    team: personoversikt
spec:
  image: {{ image }}
  port: 8080
  team: personoversikt
  liveness:
    path: /modiabrukerdialog/internal/isAlive
    initialDelay: 50
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /modiabrukerdialog/internal/isReady
    initialDelay: 50
    timeout: 1
  resources:
    requests:
      cpu: 1000m
      memory: 4096Mi
    limits:
      cpu: 2000m
      memory: 8192Mi
  ingresses:
  {{#each ingresses}}
    - {{this}}
  {{/each}}
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 60
  prometheus:
    enabled: false
  vault:
    enabled: true
    {{#if vaultPaths}}
    paths:
      {{#each vaultPaths}}
      - kvPath: {{@key}}
        mountPath: {{this}}
      {{/each}}
    {{/if}}
  {{#if env}}
  env:
    {{#each env}}
    - name: {{@key}}
      value: "{{this}}"
    {{/each}}
  {{/if}}}