apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: modiapersonoversikt-api
  namespace: q0
  cluster: dev-fss
  labels:
    team: personoversikt
spec:
  image: docker.pkg.github.com/navikt/modiapersonoversikt-api/modiapersonoversikt-api:{{version}}
  port: 8080
  team: personoversikt
  liveness:
    path: /modiapersonoversikt-api/internal/isAlive
    initialDelay: 50
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /modiapersonoversikt-api/internal/isReady
    initialDelay: 50
    timeout: 1
  prometheus:
    enabled: true
    path: /modiapersonoversikt-api/internal/metrics
  resources:
    requests:
      cpu: 1000m
      memory: 4096Mi
    limits:
      cpu: 2000m
      memory: 8192Mi
  ingresses:
    - https://modiapersonoversikt-api-q0.nais.preprod.local
    - https://app-q0.adeo.no/modiapersonoversikt-api
    - https://modapp-q0.adeo.no/modiapersonoversikt-api
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 60
  vault:
    enabled: true
    paths:
      - kvPath: /kv/preprod/fss/modiapersonoversikt-api/q0
        mountPath: /var/run/secrets/nais.io/vault
      - kvPath: /serviceuser/data/dev/srvmodiabrukerdialog
        mountPath: /var/run/secrets/nais.io/service_user
      - kvPath: /serviceuser/data/dev/srvssolinux
        mountPath: /var/run/secrets/nais.io/ldap_user
      - kvPath: /serviceuser/data/dev/srvgosys
        mountPath: /var/run/secrets/nais.io/gosys_user