name: ..build.yaml

on: [workflow_call]

jobs:
  build:
    name: Build & publish
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      id-token: write
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Java v17.x
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17.x
          cache: maven
      - name: Setup ktlint
        uses: nbadal/action-ktlint-setup@v1
        with:
          ktlint_version: '1.2.1'
      - name: Ktlint
        run: bash ./linting.sh
      - name: Build using maven
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mvn -P ci -B test --settings .github/maven-settings.xml
          mvn -P ci -B package --settings .github/maven-settings.xml -DskipTests
      - name: Publish Docker image
        if: github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/master'
        uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: personoversikt
          image_suffix: ${{ github.workflow }}
          tag: ${{ github.sha }}
          docker_context: ${{ github.workflow }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}