name: Build, push, and deploy
  ​
on: [push]
  ​
env:
  IMAGE: docker.pkg.github.com/${{ github.repository }}/modiapersonoversikt-api:${{ github.sha }}
  ​
jobs:

build:
  name: Build
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v1
    - name: Build and publish Docker image
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        mvn -P ci -B package
  ​
push:
  name: Push Docker container
  needs: build
  if: github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/master'
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v1
    - name: Build and publish Docker image
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        docker build --tag ${IMAGE} .
        docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY} -p ${GITHUB_TOKEN}
        docker push ${IMAGE}

deploy-qa:
  name: Deploy to prod
  needs: push
  if: github.ref == 'refs/heads/dev'
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v1
    - uses: nais/deploy/actions/deploy@v1
      env:
        APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
        CLUSTER: dev-fss
        RESOURCE: deploy/naiserator-q0.yaml
          ​
deploy-prod:
  name: Deploy to prod
  needs: push
  if: github.ref == 'refs/heads/master'
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v1
    - uses: nais/deploy/actions/deploy@v1
      env:
        APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
        CLUSTER: prod-fss
        RESOURCE: deploy/naiserator.yaml
