apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: modiapersonoversikt-api
  namespace: personoversikt
  labels:
    team: personoversikt
  annotations:
    nginx.ingress.kubernetes.io/enable-access-log: "false"
spec:
  image: "{{image}}"
  port: 8080
  liveness:
    path: /modiapersonoversikt-api/internal/isAlive
    initialDelay: 50
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /modiapersonoversikt-api/internal/isReady
    initialDelay: 50
    timeout: 1
  prometheus:
    enabled: true
    path: /modiapersonoversikt-api/internal/prometheus
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: elastic
        - id: loki
  secureLogs:
    enabled: true
  resources:
    requests:
      cpu: 10m
      memory: 600Mi
    limits:
      memory: 2000Mi
  ingresses:
    - https://modiapersonoversikt-api.intern.dev.nav.no
  leaderElection: true
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 60
  azure:
    application:
      enabled: true
      tenant: trygdeetaten.no
      allowAllUsers: true
      claims:
        extra:
          - "NAVident"
  accessPolicy:
    outbound:
      external:
        - host: graph.microsoft.com
        - host: saf.dev-fss-pub.nais.io
        - host: sokos-utbetaldata.dev-fss-pub.nais.io
        - host: pdl-api.dev-fss-pub.nais.io
        - host: pdl-pip-api.dev-fss-pub.nais.io
        - host: oppgave.dev-fss-pub.nais.io
        - host: axsys.dev-fss-pub.nais.io
        - host: modiapersonoversikt-api-proxy-q1.dev-fss-pub.nais.io
        - host: personoversikt-unleash-api.nav.cloud.nais.io
        - host: pensjon-pen-q2.dev-fss-pub.nais.io
      rules:
        - application: modia-soknadsstatus-api
        - application: sf-henvendelse-api-proxy
          namespace: teamnks
        - namespace: tpts
          application: tiltakspenger-datadeling
        - namespace: org
          application: norg2
        - namespace: poao
          application: veilarboppfolging
        - namespace: team-rocket
          application: kodeverk-api
        - namespace: team-rocket
          application: digdir-krr-proxy
        - namespace: min-side
          application: tms-event-api
        - namespace: nom
          application: skjermede-personer-pip
        - namespace: nom
          application: nom-api
        - namespace: okonomi
          application: sokos-kontoregister-person
        - application: repr-api
          namespace: repr
        - application: veilarbvedtaksstotte
          namespace: obo
        - application: populasjonstilgangskontroll
          namespace: tilgangsmaskin
        - application: api-intern
          namespace: aap
    inbound:
      rules:
        - application: modiapersonoversikt
          namespace: personoversikt
          cluster: dev-gcp
  envFrom:
    - secret: modiapersonoversikt-api-unleash-api-token
  env:
    - name: APP_ENVIRONMENT_NAME
      value: "q2"
    - name: MS_GRAPH_URL
      value: "https://graph.microsoft.com/"
    - name: MS_GRAPH_SCOPE
      value: "https://graph.microsoft.com/.default"
    - name: FELLES_KODEVERK_URL
      value: "http://kodeverk-api.team-rocket"
    - name: FELLES_KODEVERK_SCOPE
      value: "dev-gcp:team-rocket:kodeverk-api"
    - name: SAF_GRAPHQL_URL
      value: "https://saf-q2.dev-fss-pub.nais.io/graphql"
    - name: SAF_HENTDOKUMENT_URL
      value: "https://saf-q2.dev-fss-pub.nais.io/rest/hentdokument"
    - name: SAF_SCOPE
      value: "dev-fss:teamdokumenthandtering:saf"
    - name: SERVER_DREK_URL
      value: "https://pdl-web.dev.intern.nav.no/rekvirerdnummer"
    - name: SERVER_NORG2_FRONTEND_URL
      value: "https://norg2-frontend.ekstern.dev.nav.no"
    - name: REST_UTBETALING_ENDPOINTURL
      value: "https://sokos-utbetaldata.dev-fss-pub.nais.io/utbetaldata/api"
    - name: UTBETALING_SCOPE
      value: "dev-fss:okonomi:sokos-utbetaldata"
    - name: VEILARBOPPFOLGINGAPI_URL
      value: "http://veilarboppfolging.poao/veilarboppfolging/api"
    - name: VEILARBOPPFOLGINGAPI_SCOPE
      value: "dev-gcp:poao:veilarboppfolging"
    - name: VEILARBVEDTAKSTOTTEAPI_URL
      value: "http://veilarbvedtaksstotte.obo/veilarbvedtaksstotte"
    - name: VEILARBVEDTAKSTOTTEAPI_SCOPE
      value: "dev-gcp:obo:veilarbvedtaksstotte"
    - name: PENSJON_API_PROXY_URL
      value: "https://pensjon-pen-q2.dev-fss-pub.nais.io"
    - name: PENSJON_API_PROXY_SCOPE
      value: "dev-fss:pensjon-q2:pensjon-pen-q2"
    - name: KRR_REST_URL
      value: "http://digdir-krr-proxy.team-rocket/"
    - name: KRR_SCOPE
      value: "dev-gcp:team-rocket:digdir-krr-proxy"
    - name: KONTOREGISTER_REST_URL
      value: "http://sokos-kontoregister-person.okonomi/api/system"
    - name: KONTOREGISTER_SCOPE
      value: "dev-gcp:okonomi:sokos-kontoregister-person"
    - name: SF_HENVENDELSE_URL
      value: "http://sf-henvendelse-api-proxy.teamnks/api"
    - name: SF_HENVENDELSE_SCOPE
      value: "dev-gcp:teamnks:sf-henvendelse-api-proxy"
    - name: PDL_API_URL
      value: "https://pdl-api.dev-fss-pub.nais.io/graphql"
    - name: PDL_SCOPE
      value: "dev-fss:pdl:pdl-api"
    - name: PDL_PIP_URL
      value: "https://pdl-pip-api.dev-fss-pub.nais.io"
    - name: PDL_PIP_SCOPE
      value: "dev-fss:pdl:pdl-pip-api"
    - name: PDL_FULLMAKT_URL
      value: "http://repr-api.repr"
    - name: PDL_FULLMAKT_SCOPE
      value: "dev-gcp:repr:repr-api"
    - name: PERSONFORVALTER_URL
      value: "https://pdl-web.dev.intern.nav.no/endreperson"
    - name: OPPGAVE_BASEURL
      value: "https://oppgave.dev-fss-pub.nais.io"
    - name: OPPGAVE_SCOPE
      value: "dev-fss:oppgavehandtering:oppgave"
    - name: NORG2_BASEURL
      value: "http://norg2.org/norg2"
    - name: SAKSOVERSIKT_PRODSETTNINGSDATO
      value: "2016-06-04"
    - name: INTERNAL_TILGANG
      value: "Z990351,Z994123,Z994404,Z994673"
    - name: CXF_SECURE_LOG
      value: "enabled"
    - name: AXSYS_URL
      value: "https://axsys.dev-fss-pub.nais.io"
    - name: AXSYS_SCOPE
      value: "dev-fss:org:axsys"
    - name: AAP_URL
      value: "http://api-intern.aap"
    - name: AAP_SCOPE
      value: "dev-gcp:aap:api-intern"
    - name: NOM_URL
      value: "http://nom-api.nom"
    - name: NOM_SCOPE
      value: "dev-gcp:nom:nom-api"
    - name: SKJERMEDE_PERSONER_PIP_URL
      value: "http://skjermede-personer-pip.nom"
    - name: SKJERMEDE_PERSONER_SCOPE
      value: "dev-gcp:nom:skjermede-personer-pip"
    - name: TMS_EVENT_API_URL
      value: "http://tms-event-api.min-side/tms-event-api"
    - name: TMS_EVENT_API_SCOPE
      value: "dev-gcp:min-side:tms-event-api"
    - name: MODIA_SOKNADSSTATUS_API_URL
      value: "http://modia-soknadsstatus-api"
    - name: MODIA_SOKNADSSTATUS_SCOPE
      value: "dev-gcp:personoversikt:modia-soknadsstatus-api"
    - name: MODIAPERSONOVERSIKT_API_PROXY_URL
      value: "https://modiapersonoversikt-api-proxy-q1.dev-fss-pub.nais.io"
    - name: MODIAPERSONOVERSIKT_API_PROXY_SCOPE
      value: "dev-fss:personoversikt:modiapersonoversikt-api-proxy-q1"
    - name: UNLEASH_ENVIRONMENT
      value: "development"
    - name: TILTAKSPENGER_URL
      value: "http://tiltakspenger-datadeling.tpts"
    - name: TILTAKSPENGER_SCOPE
      value: "dev-gcp:tpts:tiltakspenger-datadeling"
    - name: TILGANGSMASKINEN_URL
      value: "http://populasjonstilgangskontroll.tilgangsmaskin"
    - name: TILGANGSMASKINEN_SCOPE
      value: "dev-gcp:tilgangsmaskin:populasjonstilgangskontroll"
