apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: modiapersonoversikt-api-q0
  namespace: personoversikt
  labels:
    team: personoversikt
  annotations:
    nginx.ingress.kubernetes.io/enable-access-log: "false"
spec:
  envFrom:
    - secret: modiapersonoversikt-api-unleash-api-token
  image: "{{image}}"
  port: 8080
  liveness:
    path: /modiapersonoversikt-api/internal/isAlive
    initialDelay: 50
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /modiapersonoversikt-api/internal/isReady
    initialDelay: 50
    timeout: 1
  prometheus:
    enabled: true
    path: /modiapersonoversikt-api/internal/prometheus
  secureLogs:
    enabled: true
  resources:
    requests:
      cpu: 1000m
      memory: 4096Mi
    limits:
      cpu: 2000m
      memory: 8192Mi
  ingresses:
    - https://modiapersonoversikt-api-q0.nais.preprod.local
    - https://app-q0.adeo.no/modiapersonoversikt-api
    - https://modapp-q0.adeo.no/modiapersonoversikt-api
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 60
  maskinporten:
    enabled: true
    scopes:
      consumes:
        - name: "skatteetaten:innkrevingsoppdrag"
  vault:
    enabled: true
    paths:
      - kvPath: /serviceuser/data/dev/srvmodiabrukerdialog
        mountPath: /var/run/secrets/nais.io/service_user
      - kvPath: /serviceuser/data/dev/srvssolinux
        mountPath: /var/run/secrets/nais.io/srvssolinux
      - kvPath: /apikey/appdynamics/dev
        mountPath: /var/run/secrets/nais.io/vault
  leaderElection: true
  webproxy: true
  azure:
    application:
      enabled: true
      tenant: trygdeetaten.no
      allowAllUsers: true
      claims:
        extra:
          - "NAVident"
  accessPolicy:
    outbound:
      external:
        - host: personoversikt-unleash-api.nav.cloud.nais.io
        - host: api-test.sits.no # Skatteetaten
    inbound:
      rules:
        - application: modiapersonoversikt-q0
          namespace: personoversikt
          cluster: dev-fss
  env:
    - name: APP_ENVIRONMENT_NAME
      value: "q0"
    - name: MS_GRAPH_URL
      value: "https://graph.microsoft.com/"
    - name: MS_GRAPH_SCOPE
      value: "https://graph.microsoft.com/.default"
    - name: FELLES_KODEVERK_URL
      value: "https://kodeverk-api.nav.no"
    - name: SAF_GRAPHQL_URL
      value: "https://saf-q0.nais.preprod.local/graphql"
    - name: SAF_HENTDOKUMENT_URL
      value: "https://saf-q0.nais.preprod.local/rest/hentdokument"
    - name: SAF_SCOPE
      value: "dev-fss:teamdokumenthandtering:saf-q0"
    - name: SERVER_DREK_URL
      value: "https://pdl-web.dev.intern.nav.no/rekvirerdnummer"
    - name: SERVER_NORG2_FRONTEND_URL
      value: "https://norg2-frontend.intern.dev.nav.no"
    - name: REST_UTBETALING_ENDPOINTURL
      value: "https://sokos-utbetaldata.dev.intern.nav.no/utbetaldata/api"
    - name: UTBETALING_SCOPE
      value: "dev-fss:okonomi:sokos-utbetaldata"
    - name: VEILARBOPPFOLGINGAPI_URL
      value: "https://veilarboppfolging.dev.intern.nav.no/veilarboppfolging/api"
    - name: VEILARBOPPFOLGINGAPI_SCOPE
      value: "dev-fss:pto:veilarboppfolging"
    - name: KRR_REST_URL
      value: "https://digdir-krr-proxy.intern.dev.nav.no/"
    - name: KRR_SCOPE
      value: "dev-gcp:team-rocket:digdir-krr-proxy"
    - name: KONTOREGISTER_REST_URL
      value: "https://sokos-kontoregister-person.intern.dev.nav.no/api/system"
    - name: KONTOREGISTER_SCOPE
      value: "dev-gcp:okonomi:sokos-kontoregister-person"
    - name: SF_HENVENDELSE_URL
      value: "https://sf-henvendelse-api-proxy.dev.intern.nav.no/api"
    - name: SF_HENVENDELSE_SCOPE
      value: "dev-fss:teamnks:sf-henvendelse-api-proxy"
    - name: PDL_API_URL
      value: "https://pdl-api-q0.dev.intern.nav.no/graphql"
    - name: PDL_SCOPE
      value: "dev-fss:pdl:pdl-api"
    - name: PDL_PIP_URL
      value: "https://pdl-pip-api-q0.dev.intern.nav.no"
    - name: PDL_PIP_SCOPE
      value: "dev-fss:pdl:pdl-pip-api-q0"
    - name: PERSONFORVALTER_URL
      value: "https://pdl-web.dev.intern.nav.no/endreperson"
    - name: OPPGAVE_BASEURL
      value: "https://oppgave-q0.dev.intern.nav.no"
    - name: OPPGAVE_SCOPE
      value: "dev-fss:oppgavehandtering:oppgave-q0"
    - name: NORG2_BASEURL
      value: "https://norg2.intern.dev.nav.no"
    - name: SAKSOVERSIKT_PRODSETTNINGSDATO
      value: "2016-06-04"
    - name: INTERNAL_TILGANG
      value: "Z990351,Z994123,Z994404"
    - name: CXF_SECURE_LOG
      value: "enabled"
    - name: AXSYS_URL
      value: "https://axsys.dev.adeo.no"
    - name: AXSYS_SCOPE
      value: "dev-fss:org:axsys"
    - name: NOM_URL
      value: "https://nom-api.intern.dev.nav.no"
    - name: NOM_SCOPE
      value: "dev-gcp:nom:nom-api"
    - name: SKJERMEDE_PERSONER_PIP_URL
      value: "https://skjermede-personer-pip.intern.dev.nav.no"
    - name: SKJERMEDE_PERSONER_SCOPE
      value: "dev-gcp:nom:skjermede-personer-pip"
    - name: TMS_EVENT_API_URL
      value: "https://tms-event-api.ekstern.dev.nav.no/tms-event-api"
    - name: TMS_EVENT_API_SCOPE
      value: "dev-gcp:min-side:tms-event-api"
    - name: MODIA_SOKNADSSTATUS_API_URL
      value: "https://modia-soknadsstatus-api.intern.dev.nav.no"
    - name: MODIA_SOKNADSSTATUS_SCOPE
      value: "dev-gcp:personoversikt:modia-soknadsstatus-api"
    - name: MODIAPERSONOVERSIKT_API_PROXY_URL
      value: "https://modiapersonoversikt-api-proxy-q0.intern.dev.nav.no"
    - name: MODIAPERSONOVERSIKT_API_PROXY_SCOPE
      value: "dev-fss:personoversikt:modiapersonoversikt-api-proxy-q0"
    - name: UNLEASH_ENVIRONMENT
      value: "development"
    - name: SKATTEETATEN_INNKREVINGSOPPDRAG_API_BASE_URL
      value: "https://api-test.sits.no"
